[tools]
node = "24.18.0"
pnpm = "latest"
bun = "latest"
deno = "latest"
go = "latest"
"aqua:pressly/goose" = "latest"
gh = "latest"
hcloud = "latest"
wrangler = "latest"
jj = "latest"
just = "latest"
shfmt = "latest"
sqlc = "latest"
oxfmt = "latest"
marp-cli = "latest"
"npm:@tailwindcss/cli" = "latest"
