[tools]
air = "latest"
bun = "latest"
deno = "latest"
gh = "latest"
glab = { version = "latest", exe = "glab" }
glow = "latest"
go = "latest"
jj = "latest"
just = "latest"
node = "latest"
oxfmt = "latest"
pnpm = "10.33.0"
shfmt = "latest"
sqlc = "latest"
wrangler = "latest"
