# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: false

brew "ansible"
brew "ansible-lint"
brew "bash"
brew "bat"
brew "charmbracelet/tap/crush"
brew "codex"
brew "docker"
brew "dopplerhq/cli/doppler"
brew "dua-cli"
brew "eza"
brew "fd"
brew "fzf"
brew "git"
brew "glow"
brew "jj"
brew "jq"
brew "just"
brew "neovim"
brew "pandoc"
brew "pieces-cli"
brew "poppler"
brew "rclone"
brew "ripgrep"
brew "rsync"
brew "starship"
brew "stow"
brew "tmux"
brew "wget"

cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "helium-browser"
cask "obsidian"
cask "orcaslicer"
cask "proton-drive"
cask "proton-pass"
cask "raycast"
cask "readwise-ibooks"
cask "rectangle-pro"
cask "yubico-authenticator"
cask "zen-browser"
