# Framework 13 AMD internal display
monitor = eDP-1, 2880x1920@120, 240x1080, 2
# Lenovo P27h-30 external monitor
monitor = desc:Lenovo Group Limited P27h-30 V30A50CM, 2560x1440@74.78, auto-up, 1.6
# Raspberry Pi portable monitor (above laptop)
monitor = desc:Raspberry PI RPI MON156 81005586360, 1920x1080@60, 0x0, 1
