return {
	-- 'yetone/avante.nvim',
	-- event = 'VeryLazy',
	-- version = false, -- set this if you want to always pull the latest change
	-- build = 'make',
	-- dependencies = {
	--     'nvim-treesitter/nvim-treesitter',
	--     'stevearc/dressing.nvim',
	--     'nvim-lua/plenary.nvim',
	--     'MunifTanjim/nui.nvim',
	--     'nvim-telescope/telescope.nvim',
	--     'hrsh7th/nvim-cmp',
	--     'nvim-tree/nvim-web-devicons',
	--     {
	--         -- support for image pasting
	--         'HakonHarnes/img-clip.nvim',
	--         event = 'VeryLazy',
	--         opts = {
	--             -- recommended settings
	--             default = {
	--                 embed_image_as_base64 = false,
	--                 prompt_for_file_name = false,
	--                 drag_and_drop = {
	--                     insert_mode = true,
	--                 },
	--             },
	--         },
	--     },
	-- },
	-- opts = {
	--     hints = { enabled = false },
	-- },
}

-- vim: ts=2 sts=2 sw=2 et
